#!/bin/bash
BD_HOST='db3.i'
DB_NAME_ENV="'ahmed_tons',"
USER_NAME_ENV="'ahmed_tons',"
DB_PASSWORD_ENV="'LzuGP9wzBhOsPDry',"
DB_NAME='ahmed_tons'
USER_NAME='ahmed_tons'
DB_PASSWORD='LzuGP9wzBhOsPDry'
LIVE_PATH='/microcloud/domains/tondev/domains/dev10.tonsoftiles.co.uk/http/'
DEV_PATH='/microcloud/domains/tondev/domains/ahmed.tonsoftiles.co.uk/http/'
DB_TABLE='core_config_data'
URL='http://ahmed.tonsoftiles.co.uk/'